// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyMCPConfig(arg1:string):Promise<string>;

export function GetAccountReport(arg1:string):Promise<main.AccountReport>;

export function GetAppState():Promise<main.AppState>;

export function GetMCPStatus():Promise<main.MCPStatus>;

export function ListAccounts():Promise<Array<main.AccountStats>>;

export function ListActivity(arg1:number):Promise<Array<main.ActivityEntry>>;

export function LoginSession():Promise<main.LoginResult>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function ReadScreenshot(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function ScanAccount(arg1:string,arg2:number):Promise<main.SearchResult>;

export function SearchFormat(arg1:string,arg2:number):Promise<main.SearchResult>;

export function SetMCPPort(arg1:number):Promise<main.MCPStatus>;

export function StartMCPServer():Promise<main.MCPStatus>;

export function StopMCPServer():Promise<main.MCPStatus>;
