// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyMCPConfig(arg1) {
  return window['go']['main']['App']['CopyMCPConfig'](arg1);
}

export function GetAccountReport(arg1) {
  return window['go']['main']['App']['GetAccountReport'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetMCPStatus() {
  return window['go']['main']['App']['GetMCPStatus']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListActivity(arg1) {
  return window['go']['main']['App']['ListActivity'](arg1);
}

export function LoginSession() {
  return window['go']['main']['App']['LoginSession']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function ReadScreenshot(arg1) {
  return window['go']['main']['App']['ReadScreenshot'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanAccount(arg1, arg2) {
  return window['go']['main']['App']['ScanAccount'](arg1, arg2);
}

export function SearchFormat(arg1, arg2) {
  return window['go']['main']['App']['SearchFormat'](arg1, arg2);
}

export function SetMCPPort(arg1) {
  return window['go']['main']['App']['SetMCPPort'](arg1);
}

export function StartMCPServer() {
  return window['go']['main']['App']['StartMCPServer']();
}

export function StopMCPServer() {
  return window['go']['main']['App']['StopMCPServer']();
}
